/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the ConnectionDetails class.
 * @constructor
 * Connection String wrapper.
 *
 * @member {string} [connectionString] A dataset connection string.
 *
 */
class ConnectionDetails {
  constructor() {
  }

  /**
   * Defines the metadata of ConnectionDetails
   *
   * @returns {object} metadata of ConnectionDetails
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ConnectionDetails',
      type: {
        name: 'Composite',
        className: 'ConnectionDetails',
        modelProperties: {
          connectionString: {
            required: false,
            serializedName: 'connectionString',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ConnectionDetails;
