/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the Dashboard class.
 * @constructor
 * A Power BI Dashboard
 *
 * @member {string} [id] The dashboard id
 *
 * @member {string} [displayName] The dashboard display name
 *
 * @member {boolean} [isReadOnly] Is ReadOnly dashboard
 *
 * @member {string} [embedUrl] The dashboard embed url
 *
 */
class Dashboard {
  constructor() {
  }

  /**
   * Defines the metadata of Dashboard
   *
   * @returns {object} metadata of Dashboard
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Dashboard',
      type: {
        name: 'Composite',
        className: 'Dashboard',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          displayName: {
            required: false,
            serializedName: 'displayName',
            type: {
              name: 'String'
            }
          },
          isReadOnly: {
            required: false,
            serializedName: 'isReadOnly',
            type: {
              name: 'Boolean'
            }
          },
          embedUrl: {
            required: false,
            serializedName: 'embedUrl',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Dashboard;
