/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the EmbedToken class.
 * @constructor
 * Power BI Embed Token
 *
 * @member {string} [token] Embed token.
 *
 * @member {string} [tokenId] Unique token Id.
 *
 * @member {date} [expiration] Expiration time of token - in UTC.
 *
 */
class EmbedToken {
  constructor() {
  }

  /**
   * Defines the metadata of EmbedToken
   *
   * @returns {object} metadata of EmbedToken
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'EmbedToken',
      type: {
        name: 'Composite',
        className: 'EmbedToken',
        modelProperties: {
          token: {
            required: false,
            serializedName: 'token',
            type: {
              name: 'String'
            }
          },
          tokenId: {
            required: false,
            serializedName: 'tokenId',
            type: {
              name: 'String'
            }
          },
          expiration: {
            required: false,
            serializedName: 'expiration',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = EmbedToken;
