/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the GenerateTokenRequest class.
 * @constructor
 * Power BI Generate Token Request
 *
 * @member {string} [accessLevel] The dataset mode or type. Possible values
 * include: 'View', 'Edit', 'Create'
 *
 * @member {string} [datasetId] The new dataset of the rebinded report
 *
 * @member {boolean} [allowSaveAs] Allow SaveAs the report with generated
 * token.
 *
 */
class GenerateTokenRequest {
  constructor() {
  }

  /**
   * Defines the metadata of GenerateTokenRequest
   *
   * @returns {object} metadata of GenerateTokenRequest
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'GenerateTokenRequest',
      type: {
        name: 'Composite',
        className: 'GenerateTokenRequest',
        modelProperties: {
          accessLevel: {
            required: false,
            serializedName: 'accessLevel',
            type: {
              name: 'String'
            }
          },
          datasetId: {
            required: false,
            serializedName: 'datasetId',
            type: {
              name: 'String'
            }
          },
          allowSaveAs: {
            required: false,
            serializedName: 'allowSaveAs',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = GenerateTokenRequest;
