/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the Group class.
 * @constructor
 * A Power BI Group
 *
 * @member {string} [id] The group id
 *
 * @member {string} [name] The group name
 *
 * @member {boolean} [isReadOnly] Is ReadOnly group
 *
 */
class Group {
  constructor() {
  }

  /**
   * Defines the metadata of Group
   *
   * @returns {object} metadata of Group
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Group',
      type: {
        name: 'Composite',
        className: 'Group',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          isReadOnly: {
            required: false,
            serializedName: 'isReadOnly',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = Group;
