/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * @class
 * Initializes a new instance of the ImportModel class.
 * @constructor
 * The import object
 *
 * @member {string} [id] The import id
 *
 * @member {string} [name] The import name name
 *
 * @member {string} [importState] The import upload state
 *
 * @member {array} [reports] The reports associated with this import
 *
 * @member {array} [datasets] The datasets associated with this import
 *
 * @member {date} [createdDateTime] Import creation time
 *
 * @member {date} [updatedDateTime] Import last update time
 *
 */
class ImportModel {
  constructor() {
  }

  /**
   * Defines the metadata of ImportModel
   *
   * @returns {object} metadata of ImportModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Import',
      type: {
        name: 'Composite',
        className: 'ImportModel',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          importState: {
            required: false,
            serializedName: 'importState',
            type: {
              name: 'String'
            }
          },
          reports: {
            required: false,
            serializedName: 'reports',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ReportElementType',
                  type: {
                    name: 'Composite',
                    className: 'Report'
                  }
              }
            }
          },
          datasets: {
            required: false,
            serializedName: 'datasets',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'DatasetElementType',
                  type: {
                    name: 'Composite',
                    className: 'Dataset'
                  }
              }
            }
          },
          createdDateTime: {
            required: false,
            serializedName: 'createdDateTime',
            type: {
              name: 'DateTime'
            }
          },
          updatedDateTime: {
            required: false,
            serializedName: 'updatedDateTime',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = ImportModel;
