/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * @class
 * Initializes a new instance of the ODataResponseListRefresh class.
 * @constructor
 * Odata response wrapper for a Power BI Refresh history
 *
 * @member {string} [odatacontext]
 *
 * @member {array} [value] The Refresh history list
 *
 */
class ODataResponseListRefresh {
  constructor() {
  }

  /**
   * Defines the metadata of ODataResponseListRefresh
   *
   * @returns {object} metadata of ODataResponseListRefresh
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ODataResponse[List[Refresh]]',
      type: {
        name: 'Composite',
        className: 'ODataResponseListRefresh',
        modelProperties: {
          odatacontext: {
            required: false,
            serializedName: 'odata\\.context',
            type: {
              name: 'String'
            }
          },
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'RefreshElementType',
                  type: {
                    name: 'Composite',
                    className: 'Refresh'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = ODataResponseListRefresh;
