/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the Refresh class.
 * @constructor
 * A Power BI refresh history entry
 *
 * @member {string} [refreshType]
 *
 * @member {date} [startTime]
 *
 * @member {date} [endTime]
 *
 * @member {string} [serviceExceptionJson]
 *
 * @member {string} [status]
 *
 */
class Refresh {
  constructor() {
  }

  /**
   * Defines the metadata of Refresh
   *
   * @returns {object} metadata of Refresh
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Refresh',
      type: {
        name: 'Composite',
        className: 'Refresh',
        modelProperties: {
          refreshType: {
            required: false,
            serializedName: 'refreshType',
            type: {
              name: 'String'
            }
          },
          startTime: {
            required: false,
            serializedName: 'startTime',
            type: {
              name: 'DateTime'
            }
          },
          endTime: {
            required: false,
            serializedName: 'endTime',
            type: {
              name: 'DateTime'
            }
          },
          serviceExceptionJson: {
            required: false,
            serializedName: 'serviceExceptionJson',
            type: {
              name: 'String'
            }
          },
          status: {
            required: false,
            serializedName: 'status',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Refresh;
