/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the Report class.
 * @constructor
 * A Power BI Report
 *
 * @member {string} [id] The report id
 *
 * @member {string} [name] The report name
 *
 * @member {string} [webUrl] The report web url
 *
 * @member {string} [embedUrl] The report embed url
 *
 * @member {string} [datasetId] The dataset id
 *
 */
class Report {
  constructor() {
  }

  /**
   * Defines the metadata of Report
   *
   * @returns {object} metadata of Report
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Report',
      type: {
        name: 'Composite',
        className: 'Report',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          webUrl: {
            required: false,
            serializedName: 'webUrl',
            type: {
              name: 'String'
            }
          },
          embedUrl: {
            required: false,
            serializedName: 'embedUrl',
            type: {
              name: 'String'
            }
          },
          datasetId: {
            required: false,
            serializedName: 'datasetId',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Report;
