/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the Tile class.
 * @constructor
 * A Power BI Tile
 *
 * @member {string} [id] The tile id
 *
 * @member {string} [title] The dashboard display name
 *
 * @member {number} [rowSpan] number of rows a tile should span
 *
 * @member {number} [colSpan] number of columns a tile should span
 *
 * @member {string} [embedUrl] The tile embed url
 *
 * @member {string} [embedData] The tile embed data
 *
 */
class Tile {
  constructor() {
  }

  /**
   * Defines the metadata of Tile
   *
   * @returns {object} metadata of Tile
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Tile',
      type: {
        name: 'Composite',
        className: 'Tile',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          title: {
            required: false,
            serializedName: 'title',
            type: {
              name: 'String'
            }
          },
          rowSpan: {
            required: false,
            serializedName: 'rowSpan',
            type: {
              name: 'Number'
            }
          },
          colSpan: {
            required: false,
            serializedName: 'colSpan',
            type: {
              name: 'Number'
            }
          },
          embedUrl: {
            required: false,
            serializedName: 'embedUrl',
            type: {
              name: 'String'
            }
          },
          embedData: {
            required: false,
            serializedName: 'embedData',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Tile;
