/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * @class
 * Initializes a new instance of the UpdateDatasourceRequest class.
 * @constructor
 * An Update Datasource To Gateway Request
 *
 * @member {object} [credentialDetails]
 *
 * @member {string} [credentialDetails.credentials] The credentials
 *
 * @member {string} [credentialDetails.credentialType] The connection type
 *
 * @member {string} [credentialDetails.encryptedConnection] The encrypted
 * connection
 *
 * @member {string} [credentialDetails.encryptionAlgorithm] The encryption
 * algorithm
 *
 * @member {string} [credentialDetails.privacyLevel] The privacy level
 *
 */
class UpdateDatasourceRequest {
  constructor() {
  }

  /**
   * Defines the metadata of UpdateDatasourceRequest
   *
   * @returns {object} metadata of UpdateDatasourceRequest
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'UpdateDatasourceRequest',
      type: {
        name: 'Composite',
        className: 'UpdateDatasourceRequest',
        modelProperties: {
          credentialDetails: {
            required: false,
            serializedName: 'credentialDetails',
            type: {
              name: 'Composite',
              className: 'CredentialDetails'
            }
          }
        }
      }
    };
  }
}

module.exports = UpdateDatasourceRequest;
