/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the UserAccessRight class.
 * @constructor
 * A Power BI user Access Right entry
 *
 * @member {string} [accessRight]
 *
 * @member {string} [emailAddress]
 *
 */
class UserAccessRight {
  constructor() {
  }

  /**
   * Defines the metadata of UserAccessRight
   *
   * @returns {object} metadata of UserAccessRight
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'UserAccessRight',
      type: {
        name: 'Composite',
        className: 'UserAccessRight',
        modelProperties: {
          accessRight: {
            required: false,
            serializedName: 'accessRight',
            type: {
              name: 'String'
            }
          },
          emailAddress: {
            required: false,
            serializedName: 'emailAddress',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = UserAccessRight;
