/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the CloneReportRequest class.
 * @constructor
 * Power BI Clone Report Request
 * @member {string} [name] The requested report name
 * 
 * @member {string} [targetWorkspaceId] Optional parameter for specifying the
 * target workspace id
 * 
 * @member {string} [targetModelId] Optional parameter for specifying the
 * target associated model (dataset) id
 * 
 */
function CloneReportRequest() {
}

/**
 * Defines the metadata of CloneReportRequest
 *
 * @returns {object} metadata of CloneReportRequest
 *
 */
CloneReportRequest.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'CloneReportRequest',
    type: {
      name: 'Composite',
      className: 'CloneReportRequest',
      modelProperties: {
        name: {
          required: false,
          serializedName: 'name',
          type: {
            name: 'String'
          }
        },
        targetWorkspaceId: {
          required: false,
          serializedName: 'targetWorkspaceId',
          type: {
            name: 'String'
          }
        },
        targetModelId: {
          required: false,
          serializedName: 'targetModelId',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = CloneReportRequest;
