/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the CreateWorkspaceRequest class.
 * @constructor
 * A Create Workspace Request
 * @member {string} [name] The workspace name
 * 
 */
function CreateWorkspaceRequest() {
}

/**
 * Defines the metadata of CreateWorkspaceRequest
 *
 * @returns {object} metadata of CreateWorkspaceRequest
 *
 */
CreateWorkspaceRequest.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'CreateWorkspaceRequest',
    type: {
      name: 'Composite',
      className: 'CreateWorkspaceRequest',
      modelProperties: {
        name: {
          required: false,
          serializedName: 'name',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = CreateWorkspaceRequest;
