/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the RebindReportRequest class.
 * @constructor
 * Power BI Rebind Report Request
 * @member {string} [datasetId] The new dataset of the rebinded report
 * 
 */
function RebindReportRequest() {
}

/**
 * Defines the metadata of RebindReportRequest
 *
 * @returns {object} metadata of RebindReportRequest
 *
 */
RebindReportRequest.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'RebindReportRequest',
    type: {
      name: 'Composite',
      className: 'RebindReportRequest',
      modelProperties: {
        datasetId: {
          required: false,
          serializedName: 'datasetId',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = RebindReportRequest;
