/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var util = require('util');
var msRest = require('ms-rest');
var WebResource = msRest.WebResource;

/**
 * @class
 * Gateways
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the PowerBIClient.
 * Initializes a new instance of the Gateways class.
 * @constructor
 *
 * @param {PowerBIClient} client Reference to the service client.
 */
function Gateways(client) {
  this.client = client;
}

/**
 * @summary Updates the credentials for the specified datasource
 *
 * @param {string} collectionName The workspace collection name
 * 
 * @param {string} workspaceId The workspace id
 * 
 * @param {string} gatewayId The gateway id
 * 
 * @param {string} datasourceId The datasource id
 * 
 * @param {object} datasourceDelta The datasource changes
 * 
 * @param {object} [options] Optional Parameters.
 * 
 * @param {object} [options.customHeaders] Headers that will be added to the
 * request
 * 
 * @param {function} callback
 *
 * @returns {function} callback(err, result, request, response)
 *
 *                      {Error}  err        - The Error object if an error occurred, null otherwise.
 *
 *                      {object} [result]   - The deserialized result object.
 *
 *                      {object} [request]  - The HTTP Request object if an error did not occur.
 *
 *                      {stream} [response] - The HTTP Response stream if an error did not occur.
 */
Gateways.prototype.patchDatasource = function (collectionName, workspaceId, gatewayId, datasourceId, datasourceDelta, options, callback) {
  var client = this.client;
  if(!callback && typeof options === 'function') {
    callback = options;
    options = null;
  }
  if (!callback) {
    throw new Error('callback cannot be null.');
  }
  // Validate
  try {
    if (collectionName === null || collectionName === undefined || typeof collectionName.valueOf() !== 'string') {
      throw new Error('collectionName cannot be null or undefined and it must be of type string.');
    }
    if (workspaceId === null || workspaceId === undefined || typeof workspaceId.valueOf() !== 'string') {
      throw new Error('workspaceId cannot be null or undefined and it must be of type string.');
    }
    if (gatewayId === null || gatewayId === undefined || typeof gatewayId.valueOf() !== 'string') {
      throw new Error('gatewayId cannot be null or undefined and it must be of type string.');
    }
    if (datasourceId === null || datasourceId === undefined || typeof datasourceId.valueOf() !== 'string') {
      throw new Error('datasourceId cannot be null or undefined and it must be of type string.');
    }
    if (datasourceDelta === null || datasourceDelta === undefined || typeof datasourceDelta !== 'object') {
      throw new Error('datasourceDelta cannot be null or undefined and it must be of type object.');
    }
  } catch (error) {
    return callback(error);
  }

  // Construct URL
  var requestUrl = this.client.baseUri +
                   '//v1.0/collections/{collectionName}/workspaces/{workspaceId}/gateways/{gatewayId}/datasources/{datasourceId}';
  requestUrl = requestUrl.replace('{collectionName}', encodeURIComponent(collectionName));
  requestUrl = requestUrl.replace('{workspaceId}', encodeURIComponent(workspaceId));
  requestUrl = requestUrl.replace('{gatewayId}', encodeURIComponent(gatewayId));
  requestUrl = requestUrl.replace('{datasourceId}', encodeURIComponent(datasourceId));
  // trim all duplicate forward slashes in the url
  var regex = /([^:]\/)\/+/gi;
  requestUrl = requestUrl.replace(regex, '$1');

  // Create HTTP transport objects
  var httpRequest = new WebResource();
  httpRequest.method = 'PATCH';
  httpRequest.headers = {};
  httpRequest.url = requestUrl;
  // Set Headers
  if(options) {
    for(var headerName in options['customHeaders']) {
      if (options['customHeaders'].hasOwnProperty(headerName)) {
        httpRequest.headers[headerName] = options['customHeaders'][headerName];
      }
    }
  }
  httpRequest.headers['Content-Type'] = 'application/json; charset=utf-8';
  // Serialize Request
  var requestContent = null;
  var requestModel = null;
  try {
    if (datasourceDelta !== null && datasourceDelta !== undefined) {
      var requestModelMapper = {
        required: true,
        serializedName: 'datasourceDelta',
        type: {
          name: 'Object'
        }
      };
      requestModel = client.serialize(requestModelMapper, datasourceDelta, 'datasourceDelta');
      requestContent = JSON.stringify(requestModel);
    }
  } catch (error) {
    var serializationError = new Error(util.format('Error "%s" occurred in serializing the ' + 
        'payload - "%s"', error.message, util.inspect(datasourceDelta, {depth: null})));
    return callback(serializationError);
  }
  httpRequest.body = requestContent;
  // Send Request
  return client.pipeline(httpRequest, function (err, response, responseBody) {
    if (err) {
      return callback(err);
    }
    var statusCode = response.statusCode;
    if (statusCode !== 200) {
      var error = new Error(responseBody);
      error.statusCode = response.statusCode;
      error.request = msRest.stripRequest(httpRequest);
      error.response = msRest.stripResponse(response);
      if (responseBody === '') responseBody = null;
      var parsedErrorResponse;
      try {
        parsedErrorResponse = JSON.parse(responseBody);
        if (parsedErrorResponse) {
          if (parsedErrorResponse.error) parsedErrorResponse = parsedErrorResponse.error;
          if (parsedErrorResponse.code) error.code = parsedErrorResponse.code;
          if (parsedErrorResponse.message) error.message = parsedErrorResponse.message;
        }
      } catch (defaultError) {
        error.message = util.format('Error "%s" occurred in deserializing the responseBody ' + 
                         '- "%s" for the default response.', defaultError.message, responseBody);
        return callback(error);
      }
      return callback(error);
    }
    // Create Result
    var result = null;
    if (responseBody === '') responseBody = null;
    // Deserialize Response
    if (statusCode === 200) {
      var parsedResponse = null;
      try {
        parsedResponse = JSON.parse(responseBody);
        result = JSON.parse(responseBody);
        if (parsedResponse !== null && parsedResponse !== undefined) {
          var resultMapper = {
            required: false,
            serializedName: 'parsedResponse',
            type: {
              name: 'Object'
            }
          };
          result = client.deserialize(resultMapper, parsedResponse, 'result');
        }
      } catch (error) {
        var deserializationError = new Error(util.format('Error "%s" occurred in deserializing the responseBody - "%s"', error, responseBody));
        deserializationError.request = msRest.stripRequest(httpRequest);
        deserializationError.response = msRest.stripResponse(response);
        return callback(deserializationError);
      }
    }

    return callback(null, result, httpRequest, response);
  });
};


module.exports = Gateways;
